# Generated by Django 5.0.6 on 2025-12-07 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("card", "0001_initial"),
        ("core", "0006_clientsite_branch_clientsite_system_commission_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="card_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="card.cardpayment",
            ),
        ),
    ]
