# Generated by Django 5.0.6 on 2025-12-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_paymenttransaction_card_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="depositrequest",
            name="currency",
            field=models.CharField(default="TRY", max_length=10),
        ),
    ]
