# Generated by Django 5.2.8 on 2025-12-09 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_paymenttransaction_crypto_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_provider_active_for_deposits",
            field=models.BooleanField(
                default=True,
                help_text="Pasif ise bu teminci yeni yatırımlar için gösterilmez.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="limitor",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Teminci için maksimum toplam yatırım limiti (boş = limitsiz)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ProviderSettlementPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_settlement_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        limit_choices_to={"role": "PROVIDER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Teslimat Ödemesi",
                "verbose_name_plural": "Teslimat Ödemeleri",
            },
        ),
    ]
