# Generated by Django 5.2.8 on 2025-12-09 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_user_is_provider_active_for_deposits_user_limitor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providersettlementpayment",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_provider_settlements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
