# Generated by Django 5.0.6 on 2025-11-21 19:31

import branches.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("domain", models.CharField(blank=True, max_length=255)),
                (
                    "api_key",
                    models.CharField(
                        default=branches.models.generate_api_key,
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "callback_url",
                    models.URLField(
                        help_text="Where we POST transaction status (approved/rejected) for this branch"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Login user for this branch/site panel",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
