# Generated by Django 5.0.6 on 2025-11-22 13:25

import branches.models
from django.db import migrations, models


def populate_site_codes(apps, schema_editor):
    Branch = apps.get_model("branches", "Branch")

    existing_codes = set(
        Branch.objects.exclude(site_code__isnull=True).values_list("site_code", flat=True)
    )

    for branch in Branch.objects.all():
        if branch.site_code:
            continue

        code = branches.models.generate_site_code()
        while code in existing_codes:
            code = branches.models.generate_site_code()

        branch.site_code = code
        branch.save(update_fields=["site_code"])
        existing_codes.add(code)


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        # 1) Add the field as nullable/non-unique so existing rows can be populated safely.
        migrations.AddField(
            model_name="branch",
            name="site_code",
            field=models.CharField(
                max_length=16,
                null=True,
                blank=True,
                help_text="Public unique ID for this site/branch (used in payment URLs).",
            ),
        ),
        # 2) Populate unique site_code values for all existing Branch records.
        migrations.RunPython(populate_site_codes, migrations.RunPython.noop),
        # 3) Enforce uniqueness and set default generator for future rows.
        migrations.AlterField(
            model_name="branch",
            name="site_code",
            field=models.CharField(
                max_length=16,
                unique=True,
                default=branches.models.generate_site_code,
                help_text="Public unique ID for this site/branch (used in payment URLs).",
            ),
        ),
    ]
