# Generated by Django 5.0.6 on 2025-11-24 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0002_branch_site_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="last_notification_ack",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="notification_poll_interval",
            field=models.PositiveIntegerField(
                default=15,
                help_text="Polling interval in seconds for site panel notifications",
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(60),
                ],
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="notification_sound_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
