# Generated by Django 5.0.6 on 2025-12-07 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0006_branch_commission_rates"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteGatewayConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("BANK", "Bank Transfer"),
                            ("CARD", "Credit Card"),
                            ("CRYPTO", "Crypto"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gateway_configs",
                        to="branches.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Gateway Configuration",
                "verbose_name_plural": "Site Gateway Configurations",
                "unique_together": {("branch", "gateway")},
            },
        ),
    ]
