# Generated by Django 5.0.6 on 2025-12-08 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0008_seed_site_gateway_configs"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardPspConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_name", models.CharField(max_length=50)),
                ("merchant_id", models.CharField(max_length=100)),
                ("terminal_id", models.CharField(blank=True, max_length=100)),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[("TEST", "Test"), ("LIVE", "Live")],
                        default="TEST",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_psp_config",
                        to="branches.branch",
                    ),
                ),
            ],
        ),
    ]
