# Generated by Django 5.0.6 on 2025-12-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("card", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardpayment",
            name="currency",
            field=models.CharField(default="TRY", max_length=10),
        ),
        migrations.AddField(
            model_name="cardpayment",
            name="psp_redirect_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cardpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("failed", "Failed"),
                    ("action_required", "Requires 3D Secure"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
