# Generated by Django 5.0.6 on 2025-12-07 22:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client_api", "0001_publicrequestlog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="publicrequestlog",
            new_name="client_api__branch__da66bd_idx",
            old_name="client_api_publicr_branch__fcad4b_idx",
        ),
    ]
