# Generated by Django 5.0.6 on 2025-12-08 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("branches", "0008_seed_site_gateway_configs"),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptoPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coin", models.CharField(max_length=20)),
                ("network", models.CharField(max_length=20)),
                ("amount", models.DecimalField(decimal_places=6, max_digits=14)),
                ("currency", models.CharField(default="TRY", max_length=10)),
                ("address", models.CharField(max_length=120)),
                ("tx_hash", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crypto_payments",
                        to="branches.branch",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
