# Generated by Django 5.0.6 on 2025-12-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptoAssetConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coin",
                    models.CharField(
                        choices=[
                            ("USDT", "USDT · Tether"),
                            ("USDC", "USDC · USD Coin"),
                            ("BTC", "BTC · Bitcoin"),
                            ("ETH", "ETH · Ethereum"),
                            ("TRX", "TRX · Tron"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("TRC20", "TRON · TRC-20"),
                            ("ERC20", "Ethereum · ERC-20"),
                            ("BEP20", "BNB Chain · BEP-20"),
                            ("MAINNET", "Mainnet"),
                        ],
                        max_length=20,
                    ),
                ),
                ("wallet_address", models.CharField(max_length=255)),
                ("tag_or_memo", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rate_source",
                    models.CharField(
                        choices=[("coingecko", "CoinGecko")],
                        default="coingecko",
                        max_length=50,
                    ),
                ),
                (
                    "manual_rate",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "rate_markup_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("min_confirmations", models.PositiveIntegerField(default=1)),
                (
                    "last_rate",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                ("last_rate_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["coin", "network"],
                "unique_together": {("coin", "network")},
            },
        ),
    ]
