# Generated by Django 5.0.6 on 2025-12-08 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0008_seed_site_gateway_configs"),
        ("crypto", "0002_cryptoassetconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptopayment",
            name="direction",
            field=models.CharField(
                choices=[("IN", "Deposit"), ("OUT", "Withdrawal")],
                default="IN",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cryptopayment",
            name="address",
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name="cryptopayment",
            name="amount",
            field=models.DecimalField(decimal_places=8, max_digits=16),
        ),
        migrations.CreateModel(
            name="CryptoWalletConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual External Wallet"),
                            ("LEDGER", "Ledger Cold Wallet"),
                        ],
                        default="MANUAL",
                        max_length=10,
                    ),
                ),
                ("coin", models.CharField(max_length=20)),
                ("network", models.CharField(max_length=20)),
                ("address", models.CharField(blank=True, max_length=180)),
                ("memo_tag", models.CharField(blank=True, max_length=120)),
                ("ledger_xpub", models.CharField(blank=True, max_length=255)),
                ("derivation_index", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crypto_wallets",
                        to="branches.branch",
                    ),
                ),
            ],
            options={
                "ordering": ["branch", "coin", "network"],
                "unique_together": {("branch", "coin", "network")},
            },
        ),
    ]
