# Generated by Django 5.2.8 on 2025-12-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto", "0005_add_payment_token_to_cryptopayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptopayment",
            name="user_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="cryptopayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
